# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://cartecovid19.bellebouffe.com
title: Manger local à Lyon pendant COVID-19
email: contact@bellebouffe.com
author: Bellebouffe / Zéro Déchet Lyon
description: "Pour être solidaire avec celles et ceux qui nous nourrissent et permettre à qui veut d'accéder à des informations pour bien se nourrir même en temps de confinement : BelleBouffe et Zéro Déchet Lyon vous proposent cette carte pour identifier les producteurs, maraichers, épiceries autour de Lyon et ses alentours. L'occasion de consommer local durant le confinement en respectant les mesures sanitaires. BelleBouffe et Zéro Déchet vous invitent à respecter ces dernières pour cette période !"
credits: 'Credits: Landing Page est un thème Bootstrap open source et gratuit créé par <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

