# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://cartecovid19.bellebouffe.com
baseurl: ""
title: Manger local à Lyon durant COVID#2
email: bonjour@bellebouffe.com
author: BelleBouffe / Zéro Déchet Lyon
description: "Le confinement ? C’est reparti ! Suite aux annonces du 28/10/2020 par le gouvernement français d'un nouveau confinement, BelleBouffe et Zéro Déchet Lyon ont décidé de relancer cette carte qui vous a servi durant le confinement du printemps dernier. Notre objectif reste le même : rescenser les producteurs, distributeurs et (c'est nouveau pour cette V2) les restaurateurs qui proposent de la bonne bouffe locale à Lyon et environs pendant le confinement."
credits: 'Credits: Landing Page est un thème Bootstrap open source et gratuit créé par <a href="http://startbootstrap.com/">Start Bootstrap</a>.'



# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

twitter_sharetext: "Retrouve la carte @BelleBouffe et @ZeroDechetLyon pour manger local à Lyon durant COVID-19 (mise à jour oct.20"
iframetitle: Points de vente de produits locaux

twitter_bellebouffe: BelleBouffe
facebook_bellebouffe: Bellebouffe.lyon
site_bellebouffe: bellebouffe.com

twitter_zerodechetlyon : ZeroDechetLyon
facebook_zerodechetlyon: ZeroDechetLyon
site_zerodechetlyon: zerodechetlyon.org
email_zerodechetlyon: plaidoyer@zerodechetlyon.org

# ----------------------- #
#   Plugins               #
# ----------------------- #

plugins :
  - jekyll-sitemap
