# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://cartecovid19.bellebouffe.com
baseurl: ""
title: Manger local à Lyon pendant COVID
email: bonjour@bellebouffe.com
author: Bellebouffe / Zéro Déchet Lyon
description: "Pour être solidaire avec celles et ceux qui nous nourrissent et permettre à qui veut d'accéder à des informations pour bien se nourrir, bien manger et surtout manger local, même en temps de confinement : BelleBouffe et Zéro Déchet Lyon vous proposent cette carte pour identifier les producteurs, maraichers, épiceries autour de Lyon et ses alentours. L'occasion de manger local durant le confinement en respectant les mesures sanitaires. BelleBouffe et Zéro Déchet vous invitent à respecter ces dernières pour cette période !"
credits: 'Credits: Landing Page est un thème Bootstrap open source et gratuit créé par <a href="http://startbootstrap.com/">Start Bootstrap</a>.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

twitter_sharetext: Retrouve la carte @BelleBouffe et @ZeroDechetLyon pour mange local à Lyon pendant COVID-19

twitter_bellebouffe: BelleBouffe
facebook_bellebouffe: Bellebouffe.lyon
site_bellebouffe: bellebouffe.com

twitter_zerodechetlyon : ZeroDechetLyon
facebook_zerodechetlyon: ZeroDechetLyon
site_zerodechetlyon: zerodechetlyon.org
email_zerodechetlyon: plaidoyer@zerodechetlyon.org

# ----------------------- #
#   Plugins               #
# ----------------------- #

plugins :
  - jekyll-sitemap
