# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://cartecovid19.bellebouffe.com
title: Mangez local autour de Lyon en temps de COVID-19
email: contact@bellebouffe.com
author: Bellebouffe / Zéro Déchet Lyon
description: Pour être solidaire avec celles et ceux qui nous nourrissent et permettre à qui veut d'accéder à des informations pour bien se nourrir même en temps de confinement, BelleBouffe et Zéro Déchet Lyon vous propose cette carte qui vous permettra d'identifier les prodcuteurs, maraichers, revendeurs, epiceries autour de chez vous, et ainsi pouvoir trouver des solutions pour consommer local durant le confinement tout en étant raisonnable sur les sorties. BelleBouffe et Zéro Déchet vous encourage fortement à respecter les mesures sanitaires pour cette période !
credits: 'Credits: Landing Page est un thème Bootstrap open source et gratuit créé par <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

